### ISSUE TITLE
Rename profile on sync

### ISSUE THREAD

**Issue by supergibbs** [victorskl/yawsso#50]
Not sure if a wider problem but the dotnet sdk doesn't support assuming a role with the source_profile is an SSO config. So yawsso sounds like a great workaround but the sdk decided to prioritize config file over the credentials file. When yawsso syncs I have the source_profile in both files and it still fails.  

Feature request to rename a profile on sync so I cound have `[profile rolesso]` in config and on sync it becomes `[role]` in the credentials file.

Maybe `yawsso -p rolesso:role`? From the docs, profile names "can use letters, numbers, hyphens ( - ), and underscores ( _ ), but no spaces."

Relates to https://github.com/aws/aws-sdk-net/issues/1853

**Comment by victorskl** [comment]
@supergibbs Yep; sound ok to me. Just hoping; folk won't intentionally name the _normal_ profile with colon in it! Bec it'd activate "rename" logic; if I understand correctly. Otherwise we could have _a dedicated flag_ or _a subcommand_ for this particular use case -- _rename profile on sync_ -- feature. How do you think?

My org and I, myself do not use `source_profile`; TBH. So it's all up to community user feedback. Likewise, happy to support this feature. 

Meanwhile, let me read the related issue pointer (thanks) to understand the context better.

**Comment by supergibbs** [comment]
Ya, I included a snippet from the docs that seems to say colons aren't allowed in profile names. I think this would be better so the rest of the functionality would still work without change. A flag or subcommand would limit to one profile probably or be harder to use. Thanks!

**Comment by victorskl** [comment]
> colons aren't allowed in profile names.

Ah; right. Colon should work then. I agree harder to use for flag or subcommand.

Thanks for PR; I will review and test it today or tomorrow. If all good, I will release it right after.

**Comment by victorskl** [comment]
Released

- Please upgrade like: `pip install -U yawsso==0.7.0`
- Added [user guide for this feature](https://github.com/victorskl/yawsso#rename-profile-on-sync)
